apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdk-validium-permissionless-prover
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdk-validium-permissionless-prover
    spec:
      nodeSelector:
        'beta.kubernetes.io/os': linux
      containers:
        - name: cdk-validium-permissionless-prover
          image: hermeznetwork/zkevm-prover:v2.2.0-RC4
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 50059
              name: mock_prover
            - containerPort: 50068
              name: mt
            - containerPort: 50078
              name: executor